{
 "title": "Sovereign Rollup Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "monitor",
    "label": "Monitor",
    "query": {
     "query": "label_values(da_blocks_processed_count,monitor)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Detailed Processing Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Extract, apply, and commit block ms",
   "type": "timeseries",
   "description": "The time taken after receiving the raw block from DA through STF transition and committing to the DB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sov_stf_transition_with_commit_ms_by_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apply_slot ms",
   "type": "timeseries",
   "description": "The time taken in the 'apply_slot' function only",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "sov_apply_slot_ms_by_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process slot ms",
   "type": "timeseries",
   "description": "The time taken in a complete iteration of the stf runner's main loop. This includes fetching the block, extracting the blobs, applying them to the state, and committing the changes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "sov_process_slot_ms_by_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Get extraction proof ms",
   "type": "timeseries",
   "description": "The time taken in the 'get_extraction_proof' function only",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sov_get_blob_extraction_proof_ms_by_slot",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extract Blob ms",
   "type": "timeseries",
   "description": "The time taken in the 'extract_relevant_blobs' function only",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "sov_extract_blobs_ms_by_slot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fetch blob ms",
   "type": "timeseries",
   "description": "The time taken to fetch the block from the DA layer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "sov_get_block_ms_by_slot", "legendFormat": "__auto" }
   ]
  },
  { "title": "Processsing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DA Blocks Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "targets": [
    { "expr": "sov_da_blocks_processed_count", "legendFormat": "{{monitor}} {{instance }}" }
   ]
  },
  {
   "title": "DA Blocks Processed rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "rate(sov_da_blocks_processed_count[$__rate_interval])",
     "legendFormat": "{{instance}} {{ $__rate_interval }}"
    }
   ]
  },
  {
   "title": "Batches Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sov_rollup_batches_processed_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions Processed per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "rate(sov_rollup_txns_processed_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot processing times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(sov_process_slot_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} 95th p"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sov_process_slot_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} median"
    }
   ]
  },
  {
   "title": "STF transition times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(sov_stf_transition_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} 95th p"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sov_stf_transition_sec_bucket[$__rate_interval])))",
     "legendFormat": "{{instance}} median"
    }
   ]
  },
  { "title": "Data Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sov_sync_distance", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Sync distance rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "expr": "abs(delta(sov_sync_distance[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current DA Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "targets": [
    { "expr": "sov_current_da_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Transactions per DA Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "targets": [
    { "expr": "sov_rollup_txns_per_da_block", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Schema DB get bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(schemadb_get_bytes_sum[$__rate_interval])",
     "legendFormat": "{{cf_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Schema DB batch commit bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(schemadb_batch_commit_bytes_sum[$__rate_interval])",
     "legendFormat": "{{db_name}}@{{instance}}"
    }
   ]
  },
  { "title": "Detailed Processing Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } }
 ]
}